apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-env
  namespace: refundai   
data:
  KAFKA_BROKER_URL: "kafka-broker-1.kafka.svc.cluster.local:9092"
  KAFKA_TOPIC: "auth_logging"
  KAFKA_USERNAME: ""
  KAFKA_PASSWORD: ""
  KAFKA_COUNT_TOPIC: "api_count"
  KAFKA_APP_ERROR_TOPIC: "app_error"

  DB_USER: "auth_user"
  DB_PASSWORD: "root321"
  DB_HOST: "mysql.default.svc.cluster.local"
  DB_NAME: "auth_ai"
  DB_PORT: "3306"            