apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: refundai   
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: ghcr.io/arshadm25/auth-service:v1
          ports:
            - containerPort: 8000
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: auth-service-env
      imagePullSecrets:
        - name: ghcr-secret