"""added total count to subscription

Revision ID: 3d75174f601a
Revises: a12a03fcc9a5
Create Date: 2025-02-06 19:13:58.960321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d75174f601a'
down_revision: Union[str, None] = 'a12a03fcc9a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('total_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'total_count')
    # ### end Alembic commands ###
