"""change in plan model

Revision ID: 5db5de2ed1d6
Revises: b27b4016578f
Create Date: 2025-02-05 16:02:58.143572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5db5de2ed1d6'
down_revision: Union[str, None] = 'b27b4016578f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('additional_price_per_request', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'additional_price_per_request')
    # ### end Alembic commands ###
