"""added validator to change end date

Revision ID: 99049c22ae5e
Revises: 5db5de2ed1d6
Create Date: 2025-02-05 18:22:57.002639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99049c22ae5e'
down_revision: Union[str, None] = '5db5de2ed1d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
