"""is_deleted field in plans model

Revision ID: ecec22e553db
Revises: c26788cb540a
Create Date: 2025-03-21 10:34:33.516440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecec22e553db'
down_revision: Union[str, None] = 'c26788cb540a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'is_deleted')
    # ### end Alembic commands ###
