"""relationship added in user model for subscription count

Revision ID: f33cae4c51e0
Revises: ecec22e553db
Create Date: 2025-03-26 10:31:05.123635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f33cae4c51e0'
down_revision: Union[str, None] = 'ecec22e553db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_subscription_counts_id'), 'user_subscription_counts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_subscription_counts_id'), table_name='user_subscription_counts')
    # ### end Alembic commands ###
